kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvat-sa-scc-rolebinding
  namespace: cvat
subjects:
  - kind: ServiceAccount
    name: cvat-sa
    namespace: cvat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
