apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cvat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvat
  serviceName: cvat
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: cvat
    spec:
      containers:
      - name: cvat
        image: openvino/cvat_server:v2.1.0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: CVAT_POSTGRES_HOST
          value: cvat-db
        - name: ALLOWED_HOSTS
          value: '*'
        - name: CVAT_REDIS_HOST
          value: cvat-redis
        - name: ADAPTIVE_AUTO_ANNOTATION
          value: 'false'
        - name: CVAT_SHARE_URL
          value: Mounted data
        volumeMounts:
        - name: cvat-data
          mountPath: /home/django/data
        - name: cvat-keys
          mountPath: /home/django/keys
        - name: cvat-logs
          mountPath: /home/django/logs
        - name: cvat-share
          mountPath: /home/django/share
          readOnly: true
        resources: {}
        securityContext:
          fsGroup: 1000
      volumes:
      - name: cvat-data
        persistentVolumeClaim:
          claimName: cvat-data
      - name: cvat-keys
        persistentVolumeClaim:
          claimName: cvat-keys
      - name: cvat-logs
        persistentVolumeClaim:
          claimName: cvat-logs
      - name: cvat-share
        persistentVolumeClaim:
          claimName: cvat-share
      tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
        effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
